CREATE DATABASE IF NOT EXISTS omsdb;
CREATE DATABASE IF NOT EXISTS wmsdb;
CREATE DATABASE IF NOT EXISTS partydb;

CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY '123456';

GRANT ALL PRIVILEGES ON omsdb.* TO 'root'@'%';
GRANT ALL PRIVILEGES ON wmsdb.* TO 'root'@'%';
GRANT ALL PRIVILEGES ON partydb.* TO 'root'@'%';

FLUSH PRIVILEGES;
